<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="BufferedWriter" Id="{45ebe690-c9fe-4552-b66c-7230e56fc137}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK BufferedWriter IMPLEMENTS Writer
VAR
	output_stream : OutputStream;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{0c17db30-de60-40da-8a30-f431c91f2bd1}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)
	output_stream : OutputStream;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.output_stream := output_stream;]]></ST>
      </Implementation>
    </Method>
    <Method Name="WriteLine" Id="{9b95e89d-3f85-4de3-b1de-57b96baf88b8}">
      <Declaration><![CDATA[METHOD PUBLIC WriteLine : BOOL
VAR_INPUT
	line : T_MaxString;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>